#!/usr/bin/env bash
set -euo pipefail

fail() {
  printf 'install: %s\n' "$1" >&2
  exit 1
}

expand_workspace_path() {
  case "$1" in
    "~") printf '%s\n' "$HOME" ;;
    "~/"*) printf '%s/%s\n' "$HOME" "${1#~/}" ;;
    *) printf '%s\n' "$1" ;;
  esac
}

choose_workspace_dir() {
  local default_dir="$1"
  local choice=""
  local selected=""
  local folder=""

  if [[ -n "${workspace_dir:-}" && "$workspace_dir" != "$default_dir" ]]; then
    printf '%s\n' "$workspace_dir"
    return 0
  fi

  if [[ ! -t 0 ]]; then
    printf '%s\n' "$default_dir"
    return 0
  fi

  printf '\nChoose a diagram workspace:\n' >&2
  printf '  1) Use current directory\n' >&2
  printf '  2) Select an existing folder\n' >&2
  printf '  3) Create a new folder\n' >&2
  printf 'Enter 1, 2, or 3 [1]: ' >&2
  read -r choice || true

  case "${choice:-1}" in
    1)
      printf '%s\n' "$default_dir"
      ;;
    2)
      printf 'Existing folder path [%s]: ' "$default_dir" >&2
      read -r selected || true
      selected="${selected:-$default_dir}"
      selected="$(expand_workspace_path "$selected")"
      [[ -d "$selected" ]] || fail "folder does not exist: $selected"
      printf '%s\n' "$selected"
      ;;
    3)
      printf 'New folder path [%s]: ' "$default_dir" >&2
      read -r folder || true
      folder="${folder:-$default_dir}"
      folder="$(expand_workspace_path "$folder")"
      mkdir -p "$folder"
      printf '%s\n' "$folder"
      ;;
    *)
      fail "unknown selection: $choice"
      ;;
  esac
}

write_workspace_config() {
  local workspace_dir="$1"
  local diagram_file="$2"
  local diagram_output="$3"
  local archive_dir="$4"
  local config_file="${workspace_dir}/.diagram-as-code.env"

  mkdir -p "$workspace_dir"
  cat > "$config_file" <<EOF
# Generated by install.sh
DIAGRAM_FILE=$(printf '%q' "$diagram_file")
DIAGRAM_OUTPUT=$(printf '%q' "$diagram_output")
DIAGRAM_ARCHIVE_DIR=$(printf '%q' "$archive_dir")
EOF
  printf 'wrote %s\n' "$config_file"
}

write_starter_diagram() {
  local workspace_dir="$1"
  local diagram_file="$2"
  local target_file="${workspace_dir}/${diagram_file}"

  if [[ -e "$target_file" ]]; then
    printf 'kept existing %s\n' "$target_file"
    return 0
  fi

  cat > "$target_file" <<'EOF'
# System Diagram

```mermaid
flowchart TD
  A[Start here] --> B[Edit this diagram]
```
EOF
  printf 'created %s\n' "$target_file"
}

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
bin_dir="${HOME}/bin"
workspace_dir="${PWD}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --workspace-dir)
      [[ $# -ge 2 ]] || fail "--workspace-dir requires a value"
      workspace_dir="$2"
      shift 2
      ;;
    --diagram-file)
      [[ $# -ge 2 ]] || fail "--diagram-file requires a value"
      diagram_file="$2"
      shift 2
      ;;
    --diagram-output)
      [[ $# -ge 2 ]] || fail "--diagram-output requires a value"
      diagram_output="$2"
      shift 2
      ;;
    --archive-dir)
      [[ $# -ge 2 ]] || fail "--archive-dir requires a value"
      archive_dir="$2"
      shift 2
      ;;
    -h|--help)
      cat <<'EOF'
Usage: ./install.sh [--workspace-dir PATH] [--diagram-file PATH] [--diagram-output PATH] [--archive-dir PATH]
EOF
      exit 0
      ;;
    *)
      fail "unknown argument: $1"
      ;;
  esac
done

workspace_dir="$(choose_workspace_dir "$workspace_dir")"
workspace_dir="$(expand_workspace_path "$workspace_dir")"
diagram_file="${diagram_file:-system-diagram.md}"
diagram_output="${diagram_output:-diagram.png}"
archive_dir="${archive_dir:-past-diagrams}"

mkdir -p "$workspace_dir"
mkdir -p "$bin_dir"

install_script() {
  local source_file="$1"
  local target_name="$2"
  local target_file="${bin_dir}/${target_name}"

  if [[ ! -f "$source_file" ]]; then
    fail "missing source script: $source_file"
  fi

  install -m 755 "$source_file" "$target_file"
  printf 'installed %s\n' "$target_file"
}

install_script "${script_dir}/scripts/render-diagram.sh" "render-diagram"
install_script "${script_dir}/scripts/archive-diagram.sh" "archive-diagram"
install_script "${script_dir}/scripts/watch-diagram.sh" "watch-diagram"
write_workspace_config "$workspace_dir" "$diagram_file" "$diagram_output" "$archive_dir"
write_starter_diagram "$workspace_dir" "$diagram_file"

path_line='export PATH="$HOME/bin:$PATH"'

case "${SHELL##*/}" in
  zsh) rc_file="${HOME}/.zshrc" ;;
  bash) rc_file="${HOME}/.bashrc" ;;
  *)
    rc_file="${HOME}/.profile"
    ;;
esac

if ! grep -Fqx "$path_line" "$rc_file" 2>/dev/null; then
  printf '%s\n' "$path_line" >> "$rc_file"
  printf 'updated %s\n' "$rc_file"
fi

printf '\nUsage:\n'
printf '  source %s\n' "$rc_file"
printf '  render-diagram\n'
printf '  watch-diagram\n'
printf '  archive-diagram\n'
