#!/usr/bin/env node
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import process from 'node:process';
import { select, input, search } from '@inquirer/prompts';

export const DEFAULT_FILES = {
  source: 'system-diagram.md',
  output: 'diagram.png',
  archiveDir: 'past-diagrams',
};

export function expandHome(value) {
  if (value === '~') return os.homedir();
  if (value.startsWith('~/')) return path.join(os.homedir(), value.slice(2));
  return value;
}

export function resolvePath(baseDir, candidate) {
  if (path.isAbsolute(candidate)) return path.normalize(candidate);
  return path.resolve(baseDir, candidate);
}

export function workspaceConfigFile(workspaceDir) {
  return path.join(workspaceDir, '.diagram-as-code.env');
}

export function findWorkspaceConfigDir(startDir = process.cwd()) {
  let dir = path.resolve(startDir);
  while (true) {
    if (fsSync.existsSync(workspaceConfigFile(dir))) {
      return dir;
    }
    if (dir === path.dirname(dir)) break;
    dir = path.dirname(dir);
  }
  return null;
}

async function pathExists(target) {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}

export async function readRegistry() {
  const file = path.join(os.homedir(), '.config', 'diagram-as-code', 'workspaces');
  try {
    const raw = await fs.readFile(file, 'utf8');
    const lines = raw
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);

    const seen = new Set();
    const workspaces = [];
    for (const candidate of lines) {
      const workspace = expandHome(candidate);
      if (seen.has(workspace)) continue;
      if (!(await pathExists(workspace))) continue;
      if (!(await pathExists(workspaceConfigFile(workspace)))) continue;
      seen.add(workspace);
      workspaces.push(workspace);
    }
    return workspaces;
  } catch {
    return [];
  }
}

async function writeRegistry(workspaces) {
  const file = path.join(os.homedir(), '.config', 'diagram-as-code', 'workspaces');
  await fs.mkdir(path.dirname(file), { recursive: true });
  const content = `${workspaces.join('\n')}${workspaces.length ? '\n' : ''}`;
  await fs.writeFile(file, content, 'utf8');
}

export async function addWorkspaceToRegistry(workspaceDir) {
  const workspaces = await readRegistry();
  const normalized = path.resolve(workspaceDir);
  const next = [normalized, ...workspaces.filter((entry) => entry !== normalized)];
  await writeRegistry(next);
}

export async function ensureStarterDiagram(workspaceDir) {
  const targetFile = path.join(workspaceDir, DEFAULT_FILES.source);
  if (await pathExists(targetFile)) {
    return { created: false, targetFile };
  }

  await fs.mkdir(workspaceDir, { recursive: true });
  await fs.writeFile(
    targetFile,
    `# System Diagram\n\n\`\`\`mermaid\nflowchart TD\n  A[Start here] --> B[Edit this diagram]\n\`\`\`\n`,
    'utf8',
  );
  return { created: true, targetFile };
}

export async function ensureWorkspace(workspaceDir) {
  const normalized = path.resolve(expandHome(workspaceDir));
  await fs.mkdir(normalized, { recursive: true });
  await fs.writeFile(
    workspaceConfigFile(normalized),
    [
      '# Generated by diagram-workspace',
      `DIAGRAM_FILE=${DEFAULT_FILES.source}`,
      `DIAGRAM_OUTPUT=${DEFAULT_FILES.output}`,
      `DIAGRAM_ARCHIVE_DIR=${DEFAULT_FILES.archiveDir}`,
      '',
    ].join('\n'),
    'utf8',
  );
  const sourceResult = await ensureStarterDiagram(normalized);
  await fs.mkdir(path.join(normalized, DEFAULT_FILES.archiveDir), { recursive: true });
  await addWorkspaceToRegistry(normalized);
  return { workspaceDir: normalized, sourceResult };
}

export async function listWorkspaces() {
  const workspaces = await readRegistry();
  if (workspaces.length === 0) {
    console.log('No initialized workspaces found.');
    return [];
  }

  workspaces.forEach((workspace, index) => {
    console.log(`${index + 1}) ${workspace}`);
  });
  return workspaces;
}

export async function chooseRecentWorkspace(workspaces) {
  if (workspaces.length === 0) return null;

  return search({
    message: 'Search recent workspaces',
    source: async (term) => {
      const query = (term ?? '').toLowerCase();
      const filtered = workspaces.filter((workspace) => {
        if (!query) return true;
        return workspace.toLowerCase().includes(query) || path.basename(workspace).toLowerCase().includes(query);
      });

      return filtered.slice(0, 20).map((workspace) => ({
        value: workspace,
        name: path.basename(workspace),
        description: workspace,
        short: workspace,
      }));
    },
  });
}

export async function promptForFolder(message, defaultValue) {
  const answer = await input({
    message,
    default: defaultValue,
    validate: async (value) => {
      const resolved = resolvePath(process.cwd(), expandHome(value.trim()));
      try {
        const stat = await fs.stat(resolved);
        return stat.isDirectory() || 'That path is not a folder.';
      } catch {
        return 'That folder does not exist.';
      }
    },
  });

  return path.resolve(expandHome(answer.trim()));
}

export async function promptForNewFolder(message, defaultValue) {
  const answer = await input({
    message,
    default: defaultValue,
    validate: (value) => {
      if (!value.trim()) return 'Please enter a folder path.';
      return true;
    },
  });

  return path.resolve(expandHome(answer.trim()));
}

export async function promptForWorkspaceSelection({
  existingDefault = process.cwd(),
  newDefault = path.join(os.homedir(), 'Projects', 'diagrams'),
} = {}) {
  const registered = await readRegistry();
  const action = await select({
    message: 'What do you want to do?',
    choices: [
      { value: 'recent', name: 'Open recent workspace', description: 'Pick from saved workspaces.' },
      { value: 'browse', name: 'Browse existing folder', description: 'Choose a folder already on disk.' },
      { value: 'new', name: 'Create new workspace', description: 'Make a new workspace folder.' },
      { value: 'list', name: 'List workspaces', description: 'Show saved workspaces and exit.' },
    ],
  });

  if (action === 'list') {
    await listWorkspaces();
    return null;
  }

  if (action === 'recent') {
    const target = await chooseRecentWorkspace(registered);
    if (target) return target;
    console.log('No saved workspaces yet, switching to browse mode.');
    return promptForFolder('Workspace folder', existingDefault);
  }

  if (action === 'browse') {
    return promptForFolder('Workspace folder', existingDefault);
  }

  return promptForNewFolder('New workspace folder', newDefault);
}
