#!/usr/bin/env node
import fs from 'node:fs/promises';
import fsSync from 'node:fs';
import { spawn, spawnSync } from 'node:child_process';
import path from 'node:path';
import os from 'node:os';
import process from 'node:process';
import { fileURLToPath } from 'node:url';
import { confirm, input, search, select } from '@inquirer/prompts';
import {
  defaultNodeWorkspace,
  DEFAULT_NODE_MAX_DEPTH,
  formatWorkspaceStatusCard,
  readNodeWorkspace,
  bumpWorkspaceLayer,
  writeNodeWorkspace,
} from './node-workspace.mjs';

export const DEFAULT_FILES = {
  source: 'workspace.node.json',
  legacySource: 'system-diagram.md',
  output: 'diagram.png',
  archiveDir: 'past-diagrams',
  studio: 'workspace-studio.html',
};

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const renderScript = path.join(scriptDir, 'render-diagram.sh');
const serverScript = path.join(scriptDir, 'workspace-server.mjs');
export const PROJECT_ROOT = path.resolve(scriptDir, '..');
export const GRAPH_FILE = path.join(os.homedir(), '.config', 'diagram-as-code', 'graph.json');

export function expandHome(value) {
  if (value === '~') return os.homedir();
  if (value.startsWith('~/')) return path.join(os.homedir(), value.slice(2));
  return value;
}

export function safeCurrentWorkingDirectory() {
  try {
    return process.cwd();
  } catch {
    return os.homedir();
  }
}

export function resolvePath(baseDir, candidate) {
  if (path.isAbsolute(candidate)) return path.normalize(candidate);
  return path.resolve(baseDir, candidate);
}

export function workspaceConfigFile(workspaceDir) {
  return path.join(workspaceDir, '.diagram-as-code.env');
}

export function findWorkspaceConfigDir(startDir = safeCurrentWorkingDirectory()) {
  let dir = path.resolve(startDir);
  while (true) {
    if (fsSync.existsSync(workspaceConfigFile(dir))) {
      return dir;
    }
    if (dir === path.dirname(dir)) break;
    dir = path.dirname(dir);
  }
  return null;
}

async function pathExists(target) {
  try {
    await fs.access(target);
    return true;
  } catch {
    return false;
  }
}

export async function readRegistry() {
  const file = path.join(os.homedir(), '.config', 'diagram-as-code', 'workspaces');
  try {
    const raw = await fs.readFile(file, 'utf8');
    const lines = raw
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean);

    const seen = new Set();
    const workspaces = [];
    for (const candidate of lines) {
      const workspace = expandHome(candidate);
      if (seen.has(workspace)) continue;
      if (!(await pathExists(workspace))) continue;
      if (!(await pathExists(workspaceConfigFile(workspace)))) continue;
      seen.add(workspace);
      workspaces.push(workspace);
    }
    return workspaces;
  } catch {
    return [];
  }
}

async function writeRegistry(workspaces) {
  const file = path.join(os.homedir(), '.config', 'diagram-as-code', 'workspaces');
  await fs.mkdir(path.dirname(file), { recursive: true });
  const content = `${workspaces.join('\n')}${workspaces.length ? '\n' : ''}`;
  await fs.writeFile(file, content, 'utf8');
}

function parseWorkspaceConfig(raw) {
  const config = {};
  for (const line of String(raw).split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const equalsIndex = trimmed.indexOf('=');
    if (equalsIndex === -1) continue;
    const key = trimmed.slice(0, equalsIndex).trim();
    const value = trimmed.slice(equalsIndex + 1).trim();
    if (key) config[key] = value;
  }
  return config;
}

async function readWorkspaceConfig(workspaceDir) {
  const file = workspaceConfigFile(workspaceDir);
  try {
    const raw = await fs.readFile(file, 'utf8');
    return parseWorkspaceConfig(raw);
  } catch {
    return null;
  }
}

async function writeWorkspaceConfig(workspaceDir, sourceFile) {
  await fs.writeFile(
    workspaceConfigFile(workspaceDir),
    [
      '# Generated by diagram-workspace',
      `DIAGRAM_FILE=${path.basename(sourceFile)}`,
      `DIAGRAM_OUTPUT=${DEFAULT_FILES.output}`,
      `DIAGRAM_ARCHIVE_DIR=${DEFAULT_FILES.archiveDir}`,
      '',
    ].join('\n'),
    'utf8',
  );
}

async function resolveWorkspaceSourceFile(workspaceDir) {
  const config = await readWorkspaceConfig(workspaceDir);
  if (config?.DIAGRAM_FILE) {
    return resolvePath(workspaceDir, path.basename(config.DIAGRAM_FILE));
  }

  const nodeSource = path.join(workspaceDir, DEFAULT_FILES.source);
  if (await pathExists(nodeSource)) return nodeSource;

  const legacySource = path.join(workspaceDir, DEFAULT_FILES.legacySource);
  if (await pathExists(legacySource)) return legacySource;

  return nodeSource;
}

function defaultSourceKind(sourceFile) {
  return sourceFile.endsWith('.json') ? 'node' : 'markdown';
}

function renderStarterDiagram(workspaceDir) {
  const result = spawnSync('bash', [renderScript], {
    cwd: workspaceDir,
    env: process.env,
    stdio: 'inherit',
  });

  if (result.error) {
    throw result.error;
  }

  if (result.status !== 0) {
    throw new Error(`starter render failed with exit code ${result.status}`);
  }
}

export async function renderWorkspacePreview(workspaceDir) {
  renderStarterDiagram(workspaceDir);
}

async function readGraph() {
  try {
    const raw = await fs.readFile(GRAPH_FILE, 'utf8');
    const graph = JSON.parse(raw);
    if (graph.schemaVersion !== 1) {
      return { schemaVersion: 1, edges: [] };
    }
    return {
      schemaVersion: 1,
      edges: Array.isArray(graph.edges) ? graph.edges : [],
    };
  } catch {
    return { schemaVersion: 1, edges: [] };
  }
}

async function writeGraph(graph) {
  await fs.mkdir(path.dirname(GRAPH_FILE), { recursive: true });
  await fs.writeFile(GRAPH_FILE, `${JSON.stringify(graph, null, 2)}\n`, 'utf8');
}

export async function readWorkspaceGraph() {
  return readGraph();
}

export async function readWorkspaceSummaries() {
  const workspaces = await readRegistry();
  const snapshots = await Promise.all(workspaces.map(async (workspaceDir) => {
    const snapshot = await readWorkspaceSnapshot(workspaceDir);
    const details = describeWorkspaceSnapshot(snapshot);
    return {
      workspaceDir,
      sourceFile: snapshot.sourceFile,
      sourceKind: snapshot.sourceKind,
      ...details,
    };
  }));

  return snapshots;
}

export async function addWorkspaceConnection(fromWorkspaceDir, toWorkspaceDir, label = '') {
  const from = path.resolve(expandHome(fromWorkspaceDir));
  const to = path.resolve(expandHome(toWorkspaceDir));
  if (from === to) {
    throw new Error('cannot connect a workspace to itself');
  }

  const graph = await readGraph();
  const normalizedLabel = String(label ?? '').trim();
  const edgeKey = `${from}::${to}::${normalizedLabel}`;
  const duplicate = graph.edges.some((edge) => `${edge.fromWorkspaceDir}::${edge.toWorkspaceDir}::${edge.label ?? ''}` === edgeKey);
  if (duplicate) {
    return graph;
  }

  graph.edges.push({
    id: `edge-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`,
    fromWorkspaceDir: from,
    toWorkspaceDir: to,
    label: normalizedLabel,
    createdAt: new Date().toISOString(),
  });
  await writeGraph(graph);
  return graph;
}

export function startWorkspaceSession(workspaceDir) {
  return new Promise((resolve, reject) => {
    const child = spawn(process.execPath, [serverScript, workspaceDir], {
      cwd: workspaceDir,
      stdio: 'inherit',
      env: process.env,
    });

    child.on('error', reject);
    child.on('exit', (code, signal) => {
      if (signal) {
        reject(new Error(`workspace session terminated by signal ${signal}`));
        return;
      }
      resolve(code ?? 0);
    });
  });
}

export async function addWorkspaceToRegistry(workspaceDir) {
  const workspaces = await readRegistry();
  const normalized = path.resolve(workspaceDir);
  const next = [normalized, ...workspaces.filter((entry) => entry !== normalized)];
  await writeRegistry(next);
}

export async function removeWorkspaceFromRegistry(workspaceDir) {
  const workspaces = await readRegistry();
  const normalized = path.resolve(workspaceDir);
  const next = workspaces.filter((entry) => entry !== normalized);
  await writeRegistry(next);
}

export function isProtectedWorkspace(workspaceDir) {
  return path.resolve(expandHome(workspaceDir)) === PROJECT_ROOT;
}

async function ensureNodeWorkspaceSource(workspaceDir, targetFile) {
  if (await pathExists(targetFile)) {
    return { created: false, targetFile };
  }

  const initialWorkspace = defaultNodeWorkspace(workspaceDir);
  await fs.mkdir(workspaceDir, { recursive: true });
  await writeNodeWorkspace(targetFile, initialWorkspace);
  return { created: true, targetFile };
}

async function ensureLegacyWorkspaceSource(workspaceDir, targetFile) {
  if (await pathExists(targetFile)) {
    return { created: false, targetFile };
  }

  await fs.mkdir(workspaceDir, { recursive: true });
  await fs.writeFile(
    targetFile,
    `# System Diagram\n\n\`\`\`mermaid\nflowchart TD\n  A[Start here] --> B[Edit this diagram]\n\`\`\`\n`,
    'utf8',
  );
  return { created: true, targetFile };
}

export async function ensureWorkspace(workspaceDir) {
  const normalized = path.resolve(expandHome(workspaceDir));
  await fs.mkdir(normalized, { recursive: true });

  const configExists = await pathExists(workspaceConfigFile(normalized));
  if (!configExists) {
    await writeWorkspaceConfig(normalized, path.join(normalized, DEFAULT_FILES.source));
  }

  const sourceFile = await resolveWorkspaceSourceFile(normalized);
  const sourceResult = defaultSourceKind(sourceFile) === 'node'
    ? await ensureNodeWorkspaceSource(normalized, sourceFile)
    : await ensureLegacyWorkspaceSource(normalized, sourceFile);

  await fs.mkdir(path.join(normalized, DEFAULT_FILES.archiveDir), { recursive: true });
  const outputFile = path.join(normalized, path.basename(process.env.DIAGRAM_OUTPUT ?? DEFAULT_FILES.output));
  if (sourceResult.created || !(await pathExists(outputFile))) {
    renderStarterDiagram(normalized);
  }
  await addWorkspaceToRegistry(normalized);
  return {
    workspaceDir: normalized,
    sourceResult,
    sourceFile,
    sourceKind: defaultSourceKind(sourceFile),
  };
}

export async function readWorkspaceSnapshot(workspaceDir) {
  const normalized = path.resolve(expandHome(workspaceDir));
  const sourceFile = await resolveWorkspaceSourceFile(normalized);
  const sourceKind = defaultSourceKind(sourceFile);

  if (sourceKind === 'node' && await pathExists(sourceFile)) {
    const workspace = await readNodeWorkspace(sourceFile);
    return { workspaceDir: normalized, sourceFile, sourceKind, workspace };
  }

  return {
    workspaceDir: normalized,
    sourceFile,
    sourceKind,
    workspace: null,
  };
}

export async function zoomWorkspaceLayer(workspaceDir, delta) {
  const snapshot = await readWorkspaceSnapshot(workspaceDir);
  if (snapshot.sourceKind !== 'node') {
    throw new Error('zooming is only available for node workspaces');
  }

  const workspace = await bumpWorkspaceLayer(snapshot.sourceFile, delta);
  return { ...snapshot, workspace };
}

export function describeWorkspaceSnapshot(snapshot) {
  const node = snapshot?.workspace?.node ?? null;
  if (!node) {
    return {
      title: path.basename(snapshot?.workspaceDir ?? ''),
      summary: 'Legacy workspace',
      activeLayer: null,
      maxDepth: null,
      sections: [],
    };
  }

  return {
    title: node.title ?? path.basename(snapshot.workspaceDir),
    summary: node.summary ?? '',
    activeLayer: Number.isInteger(node.activeLayer) ? node.activeLayer : 0,
    maxDepth: Number.isInteger(node.maxDepth) ? node.maxDepth : DEFAULT_NODE_MAX_DEPTH,
    sections: Array.isArray(node.sections) ? node.sections : [],
  };
}

export { formatWorkspaceStatusCard };

export async function listWorkspaces() {
  const workspaces = await readRegistry();
  if (workspaces.length === 0) {
    console.log('No initialized workspaces found.');
    return [];
  }

  workspaces.forEach((workspace, index) => {
    console.log(`${index + 1}) ${workspace}`);
  });
  return workspaces;
}

export async function chooseRegisteredWorkspace(workspaces, message = 'Search workspaces') {
  if (workspaces.length === 0) return null;

  return search({
    message,
    source: async (term) => {
      const query = (term ?? '').toLowerCase();
      const filtered = workspaces.filter((workspace) => {
        if (!query) return true;
        return workspace.toLowerCase().includes(query) || path.basename(workspace).toLowerCase().includes(query);
      });

      return filtered.slice(0, 20).map((workspace) => ({
        value: workspace,
        name: path.basename(workspace),
        description: workspace,
        short: workspace,
      }));
    },
  });
}

export async function promptForWorkspaceSelection() {
  const registered = await readRegistry();
  if (registered.length === 0) {
    console.log('No initialized workspaces found. Create one with `diagram-workspace new`.');
    return null;
  }

  return chooseRegisteredWorkspace(registered, 'Search workspaces');
}

export async function confirmWorkspaceDeletion(workspaceDir) {
  return confirm({
    message: `Delete workspace ${workspaceDir}? This removes the folder and unregisters it.`,
    default: false,
  });
}

export async function deleteWorkspace(workspaceDir) {
  const normalized = path.resolve(expandHome(workspaceDir));
  if (isProtectedWorkspace(normalized)) {
    throw new Error(`workspace is protected and cannot be deleted: ${normalized}`);
  }
  await fs.rm(normalized, { recursive: true, force: true });
  await removeWorkspaceFromRegistry(normalized);
  return normalized;
}

export async function promptForNewFolder(message, defaultValue) {
  const answer = await input({
    message,
    default: defaultValue,
    validate: (value) => {
      if (!value.trim()) return 'Please enter a folder path.';
      return true;
    },
  });

  return path.resolve(expandHome(answer.trim()));
}

async function listVisibleSubdirectories(directory) {
  const entries = await fs.readdir(directory, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .filter((name) => !name.startsWith('.'))
    .sort((a, b) => a.localeCompare(b));
}

export async function promptForWorkspaceFolder(startDir = path.join(os.homedir(), 'Projects', 'diagrams')) {
  let currentDir = path.resolve(expandHome(startDir));
  await fs.mkdir(currentDir, { recursive: true });

  while (true) {
    const subdirectories = await listVisibleSubdirectories(currentDir);
    const choices = [];

    if (currentDir !== path.parse(currentDir).root) {
      choices.push({
        value: 'parent',
        name: '..',
        description: path.dirname(currentDir),
      });
    }

    choices.push({
      value: 'use',
      name: 'Use this folder',
      description: currentDir,
    });

    choices.push({
      value: 'new',
      name: 'Create folder here',
      description: 'Make a new child folder and use it.',
    });

    for (const name of subdirectories) {
      const fullPath = path.join(currentDir, name);
      choices.push({
        value: fullPath,
        name: `📁 ${name}`,
        description: fullPath,
      });
    }

    choices.push({
      value: 'manual',
      name: 'Type a path manually',
      description: 'Enter a folder path directly.',
    });

    choices.push({
      value: 'cancel',
      name: 'Cancel',
      description: 'Abort workspace creation.',
    });

    const selection = await select({
      message: `Choose a workspace folder: ${currentDir}`,
      choices,
    });

    if (selection === 'use') {
      return currentDir;
    }

    if (selection === 'parent') {
      currentDir = path.dirname(currentDir);
      continue;
    }

    if (selection === 'new') {
      const childName = await input({
        message: 'New folder name',
        validate: (value) => {
          if (!value.trim()) return 'Please enter a folder name.';
          if (value.includes(path.sep)) return 'Please enter a single folder name, not a path.';
          return true;
        },
      });

      const targetDir = path.join(currentDir, childName.trim());
      await fs.mkdir(targetDir, { recursive: true });
      return targetDir;
    }

    if (selection === 'manual') {
      return promptForNewFolder('Workspace folder', currentDir);
    }

    if (selection === 'cancel') {
      return null;
    }

    currentDir = selection;
  }
}
